name: Build Android APK 
on:
push: 
branches: 
- main 
- master 
jobs:
build:
runs-on:
ubuntu-latest 
steps:
- name: Télécharger le projet
uses: actions/checkout@v4
- name: Installer Flutter 
uses: subosito/flutter-action@v2 
with:
flutter-version: '3.22.0'
- name:
Installer les dépendances 
run: flutter pub get 
- name:
Générer APK Release
run: flutter build apk --release
- name: Sauvegarder APK 
uses: actions/upload-artifact@v4
with:
name: DevisPro-App-APK 
path: build/app/outputs/flutter-apk/app-release.apk
